controller_list:
  - name: ""
    action_ns: mp_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - joint_2
      - joint_3
      - joint_4 
      - joint_5
      - joint_6 
      - joint_7 

  - name: ""
    action_ns: mp_m_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m 
      - joint_7_m 

  # - name: ""
  #   action_ns: /dual_arm/joint_trajectory_action
  #   type: FollowJointTrajectory
  #   joints: 
  #     - joint_2
  #     - joint_3
  #     - joint_4 
  #     - joint_5
  #     - joint_6 
  #     - joint_7 
  #     - joint_2_m
  #     - joint_3_m 
  #     - joint_4_m 
  #     - joint_5_m 
  #     - joint_6_m 
  #     - joint_7_m